from .spectral import spectral_clustering
from .bethe_hessian import spectral_clustering_bethe_hessian
from .laplacian import spectral_clustering_laplacian
from .modularity import spectral_clustering_modularity