from typing import List, Optional

from .dynamic_sbm import dynamic_stochastic_block_model
from ...typing import StaticGraph


def stochastic_block_model(
    B: List[List[float]],
    z: List[int],
    d: Optional[List[int]] = None,
    d_out: Optional[List[int]] = None,
    directed: Optional[bool] = False,
    multigraph: Optional[bool] = True,
    isolates: Optional[bool] = True,
    selfloops: Optional[bool] = False,
    create_using: Optional[StaticGraph] = None,
    seed: Optional[int] = None,
    sparse: Optional[bool] = False,
) -> StaticGraph:
    """ Generates a stochastic block model graph.
    Returns a :class:`~networkx_temporal.typing.StaticGraph` object.

    Adjacencies :math:`\\mathbf{A}` are sampled from a Poisson (default) or Bernoulli (if
    ``normal=False``) distribution based on community memberships and degree-correction factors,
    with edge probabilities computed by

    .. math::

        \\mathbb{P}(\\mathbf{A} \\vert \\mathbf{B}, \\mathbf{z}, \\mathbf{d}, \\mathbf{d_{out}}) =
        \\mathbf{\\Theta_{out}} \\; \\mathbf{C} \\; \\mathbf{B} \\;
        \\mathbf{C}^\\text{T} \\; \\mathbf{\\Theta_{in}},

    where :math:`\\mathbf{C}` is the :math:`n \\times k` community assignment matrix and
    :math:`\\mathbf{\\Theta}` are diagonal matrices of degree-correction factors given by the
    inverse square root of the sum of expected node degrees, i.e.,

    .. math::

        \\theta_{in,i} = \\frac{d_i}{\\sqrt{\\sum_{j=1}^{n} d_j}} \\quad \\text{and} \\quad
        \\theta_{out,i} = \\frac{d_{out,i}}{\\sqrt{\\sum_{j=1}^{n} d_{out,j}}}.

    If ``d_out=None``, out-degrees are generated by permuting the in-degree vector for directed
    graphs; for undirected graphs, the parameter is ignored so in-degrees are equal to out-degrees.

    .. rubric:: Example

    To generate an SBM with :math:`k=3` communities of :math:`n=15` nodes each, :math:`p=0.25`
    within-community edge probabilities and :math:`q=0.01` between-community edge probabilities:

    .. code-block:: python

        >>> import networkx_temporal as tx
        >>>
        >>> n = 15     # Nodes per community.
        >>> k = 3      # Number of communities.
        >>> p = 0.25   # Within-community edge probability.
        >>> q = 0.01   # Inter-community edge probability.
        >>>
        >>> B = tx.generate_block_matrix(k=k, p=p, q=q)
        >>> z = tx.generate_community_vector(nodes=n, k=k)
        >>> G = tx.generators.stochastic_block_model(B, z, isolates=False, seed=42)
        >>>
        >>> print(G)

        MultiDiGraph with 44 nodes and 89 edges

    .. code-block:: python

        >>> tx.draw(G,
        >>>         figsize=(3, 3),
        >>>         layout="kamada_kawai",
        >>>         node_size=75,
        >>>         node_color=z,
        >>>         title=str(G),
        >>>         with_labels=False)

    .. image:: ../../assets/figure/generators/stochastic_block_model.png
       :align: center

    .. seealso::

        The `graph-tool <https://graph-tool.skewed.de>`__ library, which provides more efficient
        implementations of advanced models with features such as hierarchical community structures.

    :param B: Block matrix with edge probabilities.
    :param z: Community vector assigning nodes to clusters.
    :param d: Vector of expected node degrees.
        For directed graphs, this sets the in-degree vector.
    :param d_out: Expected node out-degrees vector.
        For directed graphs, if unset, out-degrees are generated by permuting the in-degree vector.
        For undirected graphs, this parameter is ignored.
    :param directed: Whether edges are directed. Defaults to ``False``.
    :param multigraph: Allows parallel edges. Defaults to ``True``.
    :param isolates: Allows isolated nodes. Default is ``True``.
    :param selfloops: Allows self-loops. Defaults to ``False``.
    :param create_using: Graph constructor to use.
    :param fix_transition_prob: If ``True``, node transition probabilities refer
        to the ground truth probabilities in every snapshot. Default is ``False``.
    :param seed: Random number generator state.
    :param sparse: Whether to use sparse matrices. Default is ``False``.

    :param note: Same as :func:`~networkx_temporal.generators.dynamic_sbm` with ``t=1``.
    """
    return dynamic_stochastic_block_model(
        B, z, d, d_out,
        directed=directed,
        multigraph=multigraph,
        isolates=isolates,
        selfloops=selfloops,
        create_using=create_using,
        seed=seed,
        sparse=sparse,
    )[0]
