version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

formats:
  - pdf
  - epub
