from typing import Any, Optional, Union

import numpy as np

from ...typing import TemporalGraph


def dynamic_sbm(
    p: Union[list, np.array],
    t: Optional[int] = 1,
    d: Optional[Union[list, np.array]] = None,
    z: Optional[Union[list, np.array]] = None,
    eta: Optional[Union[list, np.array]] = None,
) -> TemporalGraph:
    """
    Returns a temporal graph generated by a dynamic stochastic block model.

    Parameters
    ----------
    p : float, list, numpy array
        The probability of connecting nodes within the same community.
    """

    assert type(p) in (float, list, np.array),\
        "The parameter `p` must be a float, list or numpy array."

    assert t is None or (type(t) == int and t > 0),\
        "The number of snapshots `t` must be a positive integer."

    assert d is None or type(d) in (float, tuple, list, np.array),\
        "The parameter `d` must be a float, tuple, list or numpy array."

    assert z is None or type(z) in (int, list, np.array),\
        "The parameter `z` must be a list or numpy array."

    assert eta is None or (type(t) == float and 0 <= eta <= 1),\
        "The parameter `eta` must be a float between 0 and 1."
